<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:ouo="http://oss.dbc.dk/ns/openupdateorder" 
	xmlns:ouow="http://oss.dbc.dk/ns/openupdateorder_wsdl" 
	targetNamespace="http://oss.dbc.dk/ns/openupdateorder_wsdl">
	<wsdl:types>
		<xs:schema elementFormDefault="qualified">
			<xs:import schemaLocation="openupdateorder.xsd" namespace="http://oss.dbc.dk/ns/openupdateorder"/>
		</xs:schema>
	</wsdl:types>
	<wsdl:message name="closeOrderRequest">
		<wsdl:part name="body" element="ouo:closeOrderRequest"/>
	</wsdl:message>
	<wsdl:message name="closeOrderResponse">
		<wsdl:part name="body" element="ouo:closeOrderResponse"/>
	</wsdl:message>
	<wsdl:portType name="closeOrderPortType">
		<wsdl:operation name="closeOrder">
			<wsdl:input message="ouow:closeOrderRequest"/>
			<wsdl:output message="ouow:closeOrderResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="closeOrderSoapBinding" type="ouow:closeOrderPortType">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="closeOrder">
			<soap:operation soapAction="closeOrder"/>
			<wsdl:input name="closeOrderRequest">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="closeOrderResponse">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="openUpdateOrderService">
		<wsdl:port name="closeOrderPortType" binding="ouow:closeOrderSoapBinding">
			<soap:address location="http://openudateorder.addi.dk"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>